### ISSUE TITLE
Couldn't install iepy through pip

### ISSUE THREAD

**Issue by sreejithc321** [machinalis/iepy#104]
I am getting this error 

 TypeError: 'encoding' is an invalid keyword argument for this function

Collecting iepy
  Using cached iepy-0.9.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nP8ujN/iepy/setup.py", line 7, in <module>
        with open(path.join(HERE, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by michaele4321** [comment]
I'm not an expert on this but I ran into the same error trying to dockerize the install process. It seemed to be caused by accidentally running python 2 instead of python 3. 

Did you follow the "create  a Virtualenv" step linked to from http://iepy.readthedocs.io/en/latest/installation.html ?

**Comment by jmansilla** [comment]
Indeed, that error appears when running on python 2, which isn't supported. 

Should be better to print a more informative error message here. Wondering how easy that would be.

**Comment by dmoisset** [comment]
Checking for a python version is not too hard, I submitted a PR that does that
