### ISSUE TITLE
iepy --download-third-party-data

### ISSUE THREAD

**Issue by JianyuZhao7** [machinalis/iepy#106]
When I input the command "iepy --download-third-party-data", the download doesn't go on and stop at some point.  I have waited for long time and have to interrupt it. The log info is as the picture shows. Could anyone help me ?

![qq 20161010180850](https://cloud.githubusercontent.com/assets/22743181/19232838/ae6174fe-8f14-11e6-9819-52f7f1c1a390.png)

**Comment by jmansilla** [comment]
Hello JianyuZhao7

I'm not completely sure what happened to you, but it seems that maybe you had some internet hiccup or something like that.
I'm testing right now and --download-thir-party-data it's working from here.

Can you try to re run such command and share here the output?

Regards

**Comment by JianyuZhao7** [comment]
@jmansilla Thanks a lot. I've already solved the problem. I try another day and succeed. May it is the internet hiccup.

**Comment by jmansilla** [comment]
Thanks for letting me know.
