### ISSUE TITLE
About runserver

### ISSUE THREAD

**Issue by JianyuZhao7** [machinalis/iepy#109]
When I try to finish the first instance for test, one problem occurs.
After I command "python bin/manage.py runserver", I try "curl "127.0.0.1:8000"  and there shows nothing at my ubuntu command lines.  
And the first step "1 - Loading the database" and the second step "2 - Pre-processing the data" are both well done.
So, could anyone can tell me how to solve it? Thanks a lot.

**Comment by jmansilla** [comment]
Hi!

You'll need to access that URL with a browser.

**Comment by JianyuZhao7** [comment]
@jmansilla
Thanks. I've tried to access the URL with Chrome just like" 114.113.233.186:8000" to browse the ubuntu server on my local win8 computer ,  but nothing occurs.
And I think the first step is to confirm whether there is any content on the ubuntu server. So I try curl "127.0.0.1:8000" . I think if the  "python bin/manage.py runserver" succeed, there will shows content. Right?

**Comment by JianyuZhao7** [comment]
@jmansilla what's more, I have to use the browser locally. Is it true?

**Comment by j0hn** [comment]
@JianyuZhao7 i'm not sure i got you correctly, but if you want to run the server on one machine and browse from another (in the same network) you have to run the server like this:

`python bin/manage.py runserver 0.0.0.0:8000`

and use the server's machine ip to browse.

If you want to browse it from a machine on another network (or over the internet) you might want to try [ngrok](https://ngrok.com/) or some sort of tunnel that can map a url to your local machine. Let me know if you need more details about this.

**Comment by JianyuZhao7** [comment]
@j0hn Thanks a lot. I've solved the problem using ngrok. What a great tool it is.
