### ISSUE TITLE
Loading StanfordCoreNLP... did not end

### ISSUE THREAD

**Issue by alonsopg** [machinalis/iepy#129]
Hey guys, I am trying to make a iepy tutorial, for this I am using the MUC-3 dataset. While performing step's 2 documentation (Pre-processing data), I noticed that while executing `preprocess.py` it neverd ends:

In:

`user@MacBook-Pro-de-User:~/Jupyter/iepy_tutorial/iepy_tutorial$ python3 bin/preprocess.py`

I got:

Out:
```

/usr/local/lib/python3.5/site-packages/sklearn/utils/fixes.py:55: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if 'order' in inspect.getargspec(np.copy)[0]:

Loading StanfordCoreNLP...
```

Any idea why this is happening, and how to solve it guys?... Note that I just have 100 documents, Thanks!

**Comment by davidjb99** [comment]
I also get this error on a mac, any fixes?
