### ISSUE TITLE
Problem after installing iepy. No module named...

### ISSUE THREAD

**Issue by jcrodriguez1989** [machinalis/iepy#133]
Hi, everyone!
I am having problems after installing iepy. I have followed _readthedocs_ installation steps. In my netbook, it works perfectly. However, I tried to install it in two desktops and there are some troubles. I am using virtualenv.

`$ python --version
Python 3.4.3
$ which python
/home/jcrodriguez/.virtualenvs/pln-2017/bin/python
$ python bin/gazettes_loader.py /home/jcrodriguez/relatedpapers/my_gazette.csv 
Traceback (most recent call last):
  File "bin/gazettes_loader.py", line 27, in <module>
    from iepy.data.models import EntityKind, GazetteItem
  File "/home/jcrodriguez/.virtualenvs/pln-2017/lib/python3.4/site-packages/iepy/data/models.py", line 13, in <module>
    from corpus.fields import ListField, ListSyntacticTreeField
ImportError: No module named 'corpus.fields'
$ l /home/jcrodriguez/.virtualenvs/pln-2017/lib/python3.4/site-packages/iepy/webui/corpus/
__init__.py   admin.py  fields.py  migrations/  serializer.py  static/     templatetags/  urls.py
__pycache__/  api.py    forms.py   models.py    signals.py     templates/  tests.py       views.py`

If I do _runserver_ and get into the url, it gives a similar error:
_No module named 'corpus.urls'_

Does anyone have an idea of what could it be happening?

thanks!
Juan C.

**Comment by jcrodriguez1989** [comment]
Solved!
In sys.path, I had a folder that contained a 'corpus' folder. So Python was trying to use it, instead of IEPY's one.

**Comment by jmansilla** [comment]
Thanks Juan
