### ISSUE TITLE
Consider removing title and url from document model

### ISSUE THREAD

**Issue by rafacarrascosa** [machinalis/iepy#58]
That, consider removing `title` and `url` fields from `iepy.data.models.IEDocument`

**Comment by jmansilla** [comment]
I like it.
And even more, I'm thinking that entire metadata field should be removed too. It's adding extra weight to the database for no gain inside iepy.

**Comment by francolq** [comment]
I agree about removing `title` and `url`. I would keep the `metadata`. In our application, we currently use it to store information that is used in our own document navigation application.

**Comment by rafacarrascosa** [comment]
Mmm... would it be possible to replace metadata and such by adding a 1-to-1 model wrt IEDocument?

That way we could remove it and encourages our users to do this "trick" the same way Django does with the User model.

**Comment by j0hn** [comment]
closing this ticket so we follow the discussion on #64
