### ISSUE TITLE
Drop metadata fields on IEDocuments

### ISSUE THREAD

**Issue by jmansilla** [machinalis/iepy#64]
Discussion started on #58, but let's move it to a separated place:

Motivation:

The entire metadata field should be removed. It's adding extra weight to the database for no gain inside iepy for the ultimate goal of information extraction.

I know it may be useful in some cases, but I believe that the core of iepy doesn't need that.

When we need to deal with hundreds of documents, it may harm performance.

Options:
 a) create an extra "DocumentMetadata", with OneToOne relation with IEDocuments, so the user that wants and uses it still have it.
 b) simply drop it.

The easiest is b), but I have no big cons with the option a), it just requires some extra work.

**Comment by francolq** [comment]
Ok for me if you go for b).
