### ISSUE TITLE
Unintentional symmetrical evidence generated when labelling

### ISSUE THREAD

**Issue by rafacarrascosa** [machinalis/iepy#66]
Somehow, when the GUI is used to label a relation that goes between same kind (ex: ORGANIZATION -> ORGANIZATION) the labeling is stored without regard for the order in which the clicks where made... like if the relation was symmetrical.

In concrete, if I label `A -> B` in the GUI (click A, then click B) the backend stores `A -> B` *and* `B -> A` in the database. Since not all relations are symmetrical, this is a bug, not a feature.

Also since it's friday afternoon and this is a bug report I have to leave a [gif here](http://thecodinglove.com/post/55281022566/when-a-bug-appears-on-friday-night).

i dont care lol bye

**Comment by j0hn** [comment]
Fixed on 8fef548a120af2f5e7fb86cbfdca5932debd8306

**Comment by rafacarrascosa** [comment]
Thanks!
