### ISSUE TITLE
Remove the deprecated tvseries example

### ISSUE THREAD

**Issue by rafacarrascosa** [machinalis/iepy#68]
There' s a  `/examples/tvseries` folder that has a deprecated example of an older version of IEPY, perhaps it should be removed

**Comment by pjhampton** [comment]
I agree, I tested it a couple of days ago and couldn't do much with it. Maybe this could be replaced with an machine learning example as the birthdate/ example is rule based?

**Comment by rafacarrascosa** [comment]
Damn, sorry about that @pjhampton , that's precisely what I wanted to avoid...
I fixed it on develop

**Comment by pjhampton** [comment]
That's no problem it was helpful in some ways!
