### ISSUE TITLE
Labels with 'subcategories' + Easily Reset

### ISSUE THREAD

**Issue by GilJ** [machinalis/iepy#83]
Hey guys,

I've been using IEPY for a while now, and it works really well!

I've got 2 questions
- My labels have some subcategories, for example, I got some labels that fall in the ```unit``` category that has some subcategories, for example: ```unit_liquid```, ```unit_solid``` and ```unit_other```, is there any way for IEPY to support this? If not, I'll just script something in my preprocess script that removes the subcategory.
- Is there an easy way to remove 'everything' i put into IEPY? I currently just ```rm -rf``` my IEPY folder, copy my preprocess script and csv and place everything in the right place. When I went to the /admin section and checked all documents in the 'ie documents' category to delete them, I got an error when actually deleting them (IE MetaData id was None for some document).

Thanks in advance,
Gilles

**Comment by j0hn** [comment]
Hi

* IEPY does not support subcategories out of the box, as you said, i think you'll have to hack something in your preprocess. If you find a good solution, it would be great if you could share it with us!

* IEPY uses Django, so If you're looking to delete all the data in the database you could use the command [flush](https://docs.djangoproject.com/en/1.7/ref/django-admin/#flush) like this:  `python bin/manage.py flush`

Hope it helps! Cheers.

**Comment by rafacarrascosa** [comment]
Hi Gilles,

I think that the easiest thing to do is to forget that `unit` exists and create new labels for each subclass.

If you want to work more: It could be useful to you problem lo label everything as `unit` and then adding a feature[0] to the classifier that differentiates `liquid`, `solid` and `other`...

Cheers!

[0] You could place your feature [here](https://github.com/machinalis/iepy/blob/develop/iepy/extraction/features.py)_ and then add it in your `json` config file.

**Comment by jmansilla** [comment]
Gilles I'm considering this issue as solved.

As J0hn said, we will be glad to receive a pull request with your implementation of subcategories.
