### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by KeironO** [machinalis/iepy#84]
Running on Ubuntu 14.04. Installed six 1.9 to no avail.
```
 keiron@W530  ~/Desktop/six-1.9.0  sudo iepy                   
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (six 1.9.0 (/usr/local/lib/python3.4/dist-packages/six-1.9.0-py3.4.egg), Requirement.parse('six==1.5.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iepy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.7'))
```

**Comment by jmansilla** [comment]
Hi there

Did this issue happen on a fresh virtualenv?


On Thu, Jul 30, 2015 at 7:21 PM, KeironO <notifications@github.com> wrote:

> Running on Ubuntu 14.04. Installed six 1.9 to no avail.
>
>  keiron@W530  ~/Desktop/six-1.9.0  sudo iepy
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
>     raise VersionConflict(dist,req) # XXX put more info here
> pkg_resources.VersionConflict: (six 1.9.0 (/usr/local/lib/python3.4/dist-packages/six-1.9.0-py3.4.egg), Requirement.parse('six==1.5.2'))
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/usr/local/bin/iepy", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
>     raise VersionConflict(dist,req) # XXX put more info here
> pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.7'))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/machinalis/iepy/issues/84>.
>



-- 
Javier Mansilla - Developer
www.machinalis.com
Skype: javier_mansilla

**Comment by KeironO** [comment]
I was accidentally using the globally installed version of iepy, which was outside of the local sandbox.

All problems solved now :D
