### ISSUE TITLE
Couldn't find the expected field names on the provided csv ['document_id', 'document_text']

### ISSUE THREAD

**Issue by zfrenchee** [machinalis/iepy#91]
If the documentation could be updated with some reference about how to put together the specific csv format, that would be much appreciated. This is the code that builds the CSV:

```
	writer = csv.DictWriter(open(filename, 'wb'),fieldnames=['document_id', 'document_text'])
	for key, value in mydict.items():
		writer.writerow({'document_id': key.encode('ascii', 'ignore'), 'document_text': value.encode('ascii', 'ignore')})
```

**Comment by francolq** [comment]
I think that should be ok.

These are all the docs we have: http://iepy.readthedocs.org/en/latest/instantiation.html#csv-importer

Here you have an example: http://cs.famaf.unc.edu.ar/~francolq/godfather.csv

**Comment by zfrenchee** [comment]
The issue I think is I needed `	writer.writeheader()` before the for loop. Making mention of that in the docs could be nice. Also adding the example to the docs could be cool.
