### ISSUE TITLE
Cannot merge entities of different kinds {<EntityKind: PERSON>, <EntityKind: LOCATION>}

### ISSUE THREAD

**Issue by VitalyShcherb** [machinalis/iepy#94]
Hello. I load the database. After that i'm running `python bin/preprocess.py`. There are some errors during processing: 

```
	Done for 109 documents
	Done for 110 documents
Cannot merge entities of different kinds {<EntityKind: LOCATION>, <EntityKind: ORGANIZATION>}
	Done for 111 documents
Cannot merge entities of different kinds {<EntityKind: PERSON>, <EntityKind: ORGANIZATION>}
	Done for 112 documents
	Done for 113 documents
	Done for 114 documents
```
IEPY  0.9.5
UBUNTU 15.10

This is document number 111:
> During the WWDC keynote today, shares of AAPL retracted lower as investors showed mixed feelings about the announcements. As of this story AAPL is down nearly 3 points, but not as bad as a few years before. With most of the major highlights to the keynote already in the wild, what else was left to impress? Even as people were filing into Moscone Apple reps were saying that today would be “magical”. Apple needs to keep a tighter lid on their next product released if they want to keep up the excitement for the WWDC keynote.

**Comment by jmansilla** [comment]
Hello there.

Those lines are not errors to worry about. Instead, are warning messages.

In the Stanford preprocess wrapper we have, after entities are detected, the code attempts to "merge correferences", ie, for the entity-occurrences sets on which there's a suspicion that they are all refering to the same entity, the system "merges" them, making all of the point to the same Entity.

On such attempts, if the entity-occurrences set contains different kinds (ie, a location, and later a person), the merge is aborted, but the entire preprocess keeps going without problems. 

Those "cannot merge" messages you saw are simply that.
