### ISSUE TITLE
Access is denied - C:\python23\lib\subprocess.py - Windows 8.1

### ISSUE THREAD

**Issue by denidzoja** [machinalis/iepy#98]
**New problem**: 
`C:\Python34\Lib>iepy
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\iepy.exe\__main__.py", line 5, in <module>
  File "c:\python34\lib\site-packages\iepy\instantiation\command_line.py", line
27, in <module>
    from iepy.preprocess.corenlp import download as download_corenlp
  File "c:\python34\lib\site-packages\iepy\preprocess\corenlp.py", line 28, in <
module>
    JAVA_VERSION = detect_java_version()
  File "c:\python34\lib\site-packages\iepy\preprocess\corenlp.py", line 24, in d
etect_java_version
    jversion = subprocess.check_output([java_cmd, "-jar", jar], stderr=subproces
s.PIPE)
  File "c:\python34\lib\subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "c:\python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "c:\python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied
`
Something is going wrong with subprocess.py - for some reason I can't access it. Even though I open cmd as an admin. This is a weird one - I've got no idea how to fix this.
----------------------------------------------------------------------------------------------------------------------------------------
**SOLVED: Create environment variable as JAVAHOME and set it to your jdk path**
**New issue:** After iepy is successfully installed through pip, I try to run iepy and I get an error
`Environment variable JAVAHOME not defined`. 

So I went to the jdk folder which in my case was: C:\Program Files\Java\jdk1.8.0_60 , and I added a new environment variable called JAVAHOME. Unfortunately, this didn't remedy the issue. I'm still working on this one. 

----------------------------------------------------------------------------------------------------------------------------------------
**SOLVED: It wasn't able to create a folder in my AppData\Local\MYUSERNAME\iepy, so I just added the folder manually.**
I'm having an issue running iepy, especially since there's no information about how to install iepy on Windows (I'm not even sure it's possible). This is the error i'm getting:

`C:\Users\Deni>iepy
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\iepy.exe\__main__.py", line 5, in <module>
  File "c:\python34\lib\site-packages\iepy\instantiation\command_line.py", line
25, in <module>
    from iepy.instantiation.instance_admin import InstanceManager
  File "c:\python34\lib\site-packages\iepy\instantiation\instance_admin.py", lin
e 11, in <module>
    from iepy import defaults
  File "c:\python34\lib\site-packages\iepy\defaults.py", line 3, in <module>
    from iepy.utils import make_feature_list
  File "c:\python34\lib\site-packages\iepy\utils.py", line 19, in <module>
    os.mkdir(DIRS.user_data_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\
Users\\Deni\\AppData\\Local\\Deni\\iepy`

Here is a list of all the dependencies I had installed before installing iepy. 

`
C:\Users\Deni>pip list
aiohttp (0.22.0a0)
appdirs (1.2.0)
asciitree (0.3.1)
attrs (15.2.0)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.4.1)
cffi (1.6.0)
chardet (2.3.0)
colorama (0.2.7)
cryptography (1.3.1)
cssselect (0.9.1)
cycler (0.10.0)
Cython (0.24)
decorator (4.0.9)
Django (1.7.6)
django-angular (0.7.8)
django-extra-views (0.7.1)
django-relatedadminwidget (0.0.3)
django-relatives (0.3.1)
docopt (0.6.1)
docutils (0.12)
factory-boy (2.4.1)
featureforge (0.1.6)
Flask (0.10.1)
future (0.11.4)
Google-Search-API (1.1.11)
googlescraper (0.2.1)
httplib2 (0.9.2)
idna (2.1)
iepy (0.9.5)
ipython (4.2.0)
ipython-genutils (0.1.0)
itsdangerous (0.24)
Jinja2 (2.8)
jsonfield (1.0.0)
Kivy (1.9.1)
Kivy-Garden (0.1.4)
kivy.deps.glew (0.1.4)
kivy.deps.gstreamer (0.1.5)
kivy.deps.sdl2 (0.1.12)
lxml (3.6.0)
Mako (1.0.4)
MarkupSafe (0.23)
matplotlib (1.5.1)
mechanize (0.2.5)
mock (2.0.0)
multidict (1.0.3)
networkx (1.11)
nltk (3.0.0)
nose (1.3.0)
nose-parameterized (0.5.0)
numpy (1.10.4)
oauth2 (1.9.0.post1)
pandas (0.18.1)
pbr (1.10.0)
pickleshare (0.7.2)
pip (8.1.2)
progress (1.2)
py (1.4.31)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.14)
Pygments (2.1.3)
pymongo (3.2.2)
pymysql (0.7.3)
pyOpenSSL (16.0.0)
pyparsing (2.1.4)
pypiwin32 (219)
pysolr (3.5.0)
pytest (2.9.1)
python-crfsuite (0.8.4)
python-dateutil (2.5.3)
pytools (2016.2.1)
pytz (2016.4)
queuelib (1.4.2)
REfO (0.13)
requests (2.10.0)
schema (0.3.1)
scikit-learn (0.15.2)
scipy (0.17.1)
Scrapy (1.0.5)
selenium (2.53.2)
sentiment-classifier (0.6)
service-identity (16.0.0)
setuptools (21.2.1)
simplegeneric (0.8.1)
six (1.10.0)
sqlalchemy (1.0.13)
theano (0.9.0.dev1)
traitlets (4.2.1)
Twisted (16.1.1)
Unidecode (0.4.19)
w3lib (1.14.2)
Werkzeug (0.11.5)
wget (2.0)
wheel (0.29.0)
Whoosh (2.7.4)
xmltodict (0.8.6)
zope.interface (4.1.3)`

I should also mention that I'm not using a virtualenv (maybe that's the problem?), and I'm not sure how to install the openjdk-7-jre on windows. I have java installed if it's the same thing.

**Comment by jmansilla** [comment]
JAVAHOME is an environment variable that needs to be defined pointing to the "java" binary by the nltk library.

Maybe this can help you http://stackoverflow.com/questions/7404720/nltk-fails-to-find-the-java-executable

Anyways, I wouldn't trust on making IEPY run on windows.

**Comment by jmansilla** [comment]
Any luck with this @denidzoja? I'm closing this ticket as wontfix
