### ISSUE TITLE
run preprocess.py  problem

### ISSUE THREAD

**Issue by Mrweak** [machinalis/iepy#99]
I have successfully installed the IEPY in my ubuntu14.04.1 linux and I also successfully imported the csv data.
But when I try to preprecess the data,it comes to the following problems:

linux@ubuntu:~/shizeshun/bin$ python3 preprocess.py
Loading StanfordCoreNLP...
Error running '/home/linux/.config/iepy/stanford-corenlp-full-2014-08-27/corenlp.sh -outputFormat xml -threads 4 -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref'
Output was: 'b'/usr/bin/java -mx3g -cp "/home/linux/.config/iepy/stanford-corenlp-full-2014-08-27/*" edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat xml -threads 4 -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref
Error occurred during initialization of VM.
Could not reserve enough space for object heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. 
Program will exit.

I think it might have been a problem for Java heap space, so I tried some ways to set up, but did not work.
Could you please give me some help with this problem?
Thank you sooooooooooo much!

**Comment by jmansilla** [comment]
Hi!

Indeed it's an issue with Java.
IEPY behind the curtain does several NLP preprocessing tasks with a Java library (Stanford CoreNLP). And it's a resource very demanding .

Can you check this troubleshooting section of our doc to see if with that you can make it work? https://iepy.readthedocs.io/en/stable/troubleshooting.html#troubleshooting

Regards

**Comment by Mrweak** [comment]
Hahaha. With your help, I solved the problem immediately.
Thank you very much!!!
